;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[module/marginsmall]
type = custom/text
content = %{T2}%{T-}
content-foreground = ${colors.trans}

[module/margin]
type = custom/text
content = %{T2}%%%%%%{T-}
content-foreground = ${colors.trans}

[module/i3]
type = internal/i3
format = <label-state> <label-mode>

label-active = 
label-active-background = ${colors.background-alt}
label-active-padding = 1

label-occupied =  
label-occupied-padding = 1

label-urgent = 
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = 
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

ws-icon-0 = 
ws-icon-1 = 
ws-icon-2 = 

[module/wlan]
type = internal/network
interface = wlp0s20f3
interface-type = wireless

label-connected = %{A1:nm-connection-editor:}直%{A}
format-connected = <label-connected>

label-disconnected = %{A1:nm-connection-editor:}睊%{A}
format-disconnected = <label-connected>

[module/xworkspaces]
type = internal/xworkspaces

label-active = 
;label-active-background = ${colors.background-alt}
label-active-padding = 1
label-active-foreground = ${colors.primary}

label-occupied =  
label-occupied-padding = 1
label-occupied-foreground = ${colors.primary}

label-urgent = 
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = 
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/battery-percent]
type = internal/battery
battery = BAT0
poll-interval = 5
format-label = <label-discharging>
format-label-background = ${colors.trans}

label-discharging = %{T3}%percentage%%%{T-}
format-discharging-foreground = ${colors.primary}

label-charging = %{T3}%percentage%%%{T-}
format-charging-foreground = ${colors.primary}

[module/battery]
type 	= internal/battery
low-at  = 5
full-at = 95
battery = BAT0
adapter = AC
poll-interval = 5

format-full = <label-full>
format-full-foreground = ${colors.primary}

format-low = <label-low>
format-low-foreground = ${colors.red}

format-charging = <animation-charging>
format-charging-foreground = ${colors.primary}

label-discharging-font = 2
format-discharging = <ramp-capacity>
format-discharging-foreground = ${colors.primary}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
ramp-capacity-alt = %percentage%%

[module/sound]
type = internal/pulseaudio

format-volume = <label-volume>
format-volume-foreground = ${colors.primary}
label-volume = 墳

format-muted = <label-percentage><label-muted>
format-muted-foreground = ${colors.primary}
label-muted = 婢

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format = <label-indicator>

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.red}
label-indicator-background = ${colors.red}

label-indicator-on-capslock-foreground = ${colors.red}
label-indicator-on-capslock = 

[module/date]
type = internal/date
interval = 1

date =  %H:%M 
date-alt =  %{T3} %Y-%m-%d %H:%M:%S%{T-}

label = %date%
label-foreground = ${colors.primary}

format = <label>

[settings]
screenchange-reload = true
pseudo-transparency = false

[module/files]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = thunar

[module/firefox]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = firefox

[module/spotify]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = spotify-launcher

[module/minecraft]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = minecraft-launcher

[module/settings]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = xfce4-settings-manager


